const quotes = [ "The greatest glory in living lies not in never falling, but in rising every time we fall. -Nelson Mandela",
"The way to get started is to quit talking and begin doing. -Walt Disney",
"Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma – which is living with the results of other people's thinking. -Steve Jobs",
"The future belongs to those who believe in the beauty of their dreams. -Eleanor Roosevelt",
"If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. -Oprah Winfrey",
"If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. -James Cameron",
"You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one. -John Lennon",
"You must be the change you wish to see in the world. -Mahatma Gandhi",
"Spread love everywhere you go. Let no one ever come to you without leaving happier. -Mother Teresa",
"The only thing we have to fear is fear itself. -Franklin D. Roosevelt",
"Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that. -Martin Luther King Jr.",
"Do one thing every day that scares you. -Eleanor Roosevelt",
"Well done is better than well said. -Benjamin Franklin",
"The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. -Helen Keller",
"It is during our darkest moments that we must focus to see the light. -Aristotle",
"Do not go where the path may lead, go instead where there is no path and leave a trail. -Ralph Waldo Emerson",
"Be yourself; everyone else is already taken. -Oscar Wilde",
"You will face many defeats in life, but never let yourself be defeated. -Maya Angelou",
"Go confidently in the direction of your dreams! Live the life you've imagined. -Henry David Thoreau",
"In the end, it's not the years in your life that count. It's the life in your years. -Abraham Lincoln",
"Never let the fear of striking out keep you from playing the game. -Babe Ruth",
"In this life we cannot do great things. We can only do small things with great love. -Mother Teresa",
"Many of life's failures are people who did not realize how close they were to success when they gave up. -Thomas A. Edison",
"You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. -Dr. Seuss",
"If life were predictable, it would cease to be life and be without flavor. -Eleanor Roosevelt",
"Life is a succession of lessons which must be lived to be understood. -Ralph Waldo Emerson",
"You will face many defeats in life, but never let yourself be defeated. -Maya Angelou",
"Never let the fear of striking out keep you from playing the game. -Babe Ruth",
"Life is never fair, and perhaps it is a good thing for most of us that it is not. -Oscar Wilde",
"The only impossible journey is the one you never begin. -Tony Robbins",
"Only a life lived for others is a life worthwhile. -Albert Einstein",
"The purpose of our lives is to be happy. -Dalai Lama",
"You only live once, but if you do it right, once is enough. -Mae West",
"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. -Ralph Waldo Emerson",
"Don't worry when you are not recognized but strive to be worthy of recognition. -Abraham Lincoln",
"The greatest glory in living lies not in never falling, but in rising every time we fall. -Nelson Mandela",
"Life is really simple, but we insist on making it complicated. -Confucius",
"May you live all the days of your life. -Jonathan Swift",
"Life itself is the most wonderful fairy tale. -Hans Christian Andersen",
"Do not let making a living prevent you from making a life. -John Wooden",
"Go confidently in the direction of your dreams! Live the life you've imagined. -Henry David Thoreau",
"Life is either a daring adventure or nothing. -Helen Keller",
"Life is a long lesson in humility. -James M. Barrie",
"In three words I can sum up everything I've learned about life: it goes on. -Robert Frost",
"Life is made of ever so many partings welded together. -Charles Dickens",
"Life is trying things to see if they work. -Ray Bradbury",
"Keep smiling, because life is a beautiful thing and there's so much to smile about. -Marilyn Monroe",
"In the depth of winter, I finally learned that within me there lay an invincible summer. -Albert Camus",
"Success is not final; failure is not fatal: It is the courage to continue that counts. -Winston S. Churchill",
"Success usually comes to those who are too busy to be looking for it. -Henry David Thoreau",
"If you want to make your dreams come true, the first thing you have to do is wake up. -J.M. Power",
"If you really look closely, most overnight successes took a long time. -Steve Jobs",
"The secret of success is to do the common thing uncommonly well. -John D. Rockefeller Jr.",
"I find that the harder I work, the more luck I seem to have. -Thomas Jefferson",
"The future belongs to those who believe in the beauty of their dreams. -Eleanor Roosevelt",
"The way to get started is to quit talking and begin doing. -Walt Disney",
"Don't be distracted by criticism. Remember — the only taste of success some people get is to take a bite out of you. -Zig Ziglar",
"Everything you can imagine is real. -Pablo Picasso",
"There are no secrets to success. It is the result of preparation, hard work, and learning from failure. -Colin Powell",
"The real test is not whether you avoid this failure, because you won't. It's whether you let it harden or shame you into inaction, or whether you learn from it; whether you choose to persevere. -Barack Obama",
"The only limit to our realization of tomorrow will be our doubts of today. -Franklin D. Roosevelt",
"It is better to fail in originality than to succeed in imitation. -Herman Melville",
"The road to success and the road to failure are almost exactly the same. -Colin R. Davis",
"Always remember, your focus determines your reality. -George Lucas",
"If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. -James Cameron",
"If you really look closely, most overnight successes took a long time. -Steve Jobs",
"To be successful, you have to be selfish, or else you will never achieve. And once you get to your highest level, then you have to be unselfish. -Michael Jordan",
"Let the future tell the truth, and evaluate each one according to his work and accomplishments. The present is theirs; the future, for which I have really worked, is mine. -Nikola Tesla",
"Try not to become a man of success. Rather become a man of value. -Albert Einstein",
"Don't be afraid to give up the good to go for the great. -John D. Rockefeller",
"Leave nothing for tomorrow which can be done today. -Abraham Lincoln",
"Success is walking from failure to failure with no loss of enthusiasm. -Winston Churchill",
"When you undervalue what you do, the world will undervalue who you are. -Oprah Winfrey",
"If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work. -Thomas J. Watson",
"If you genuinely want something, don't wait for it — teach yourself to be impatient. -Gurbaksh Chahal",
"The only place where success comes before work is in the dictionary. -Vidal Sassoon",
"If you are not willing to risk the usual, you will have to settle for the ordinary. -Jim Rohn",
"Before anything else, preparation is the key to success. -Alexander Graham Bell",
"People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. -Tony Robbins",
"Don't watch the clock; do what it does. Keep going. -Sam Levenson",
"The best revenge is massive success. -Frank Sinatra",
"It's not whether you get knocked down, it's whether you get up. -Vince Lombardi",
"The best way to predict the future is to create it. -Peter Drucker",
"It does not matter how slowly you go, so long as you do not stop. -Confucius",
"People tell you the world looks a certain way. Parents tell you how to think. Schools tell you how to think. TV. Religion. And then at a certain point, if you’re lucky, you realize you can make up your own mind. Nobody sets the rules but you. You can design your own life. - Carrie Ann Moss",
    "Some women choose to follow men, and some choose to follow their dreams. If you’re wondering which way to go, remember that your career will never wake up and tell you that it doesn’t love you anymore. - Lady Gaga",
    "Life is what happens to us while we are making other plans. - Allen Saunders",
    "Life isn’t about finding yourself. Life is about creating yourself. - George Bernard Shaw",
    "You are the sum total of everything you’ve ever seen, heard, eaten, smelled, been told, forgot ― it’s all there. Everything influences each of us, and because of that I try to make sure that my experiences are positive. - Maya Angelou",
    "Doubt kills more dreams than failure ever will. - Suzy Kassem",
    "Keep your face always toward the sunshine, and shadows will fall behind you. - Walt Whitman",
    "Whether you think you can or think you can’t, you’re right. - Henry Ford",
    "Your talent determines what you can do. Your motivation determines how much you’re willing to do. Your attitude determines how well you do it. - Lou Holtz",
    "The happiness of your life depends on the quality of your thoughts. - Marcus Aurelius",
    "Nothing is impossible. The word itself says ‘I’m possible!' - Audrey Hepburn",
    "You are who you are meant to be. Dance as if no one’s watching. Love as if it’s all you know. Dream as if you’ll live forever. Live as if you’ll die today. - James Dean",
    "You do not find the happy life. You make it. - Camilla Eyring Kimball",
    "You’ve gotta dance like there’s nobody watching, Love like you’ll never be hurt, Sing like there’s nobody listening, And live like it’s heaven on earth. - William W. Purkey",
    "Happiness is not something readymade. It comes from your own actions. - Dalai Lama",
    "Folks are usually about as happy as they make up their minds to be. - Abraham Lincoln",
    "It is during our darkest moments that we must focus to see the light. - Aristotle",
    "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. - Dale Carnegie",
    "You learn more from failure than from success. Don’t let it stop you. Failure builds character. - Unknown",
    "Fairytales do not tell children that dragons exist. Children already know that dragons exist. Fairytales tell children that dragons can be killed. - G K Chesterton",
    "The bad news is time flies. The good news is you’re the pilot. - Michael Altshuler",
    "Just because it’s what’s done doesn’t mean it’s what should be done! - Cinderella",
    "With a smile and a song, life is just like a bright sunny day. Your cares fade away. - Snow White",
    "It’s no use going back to yesterday because I was a different person then. - Alice, Alice In Wonderland",
    "When we get to the end of the story, you will know more than you do now… - Hans Christian Andersen, The Snow Queen",
    "The most important thing in life is to stop saying ‘I wish’ and start saying ‘I will’. Consider nothing impossible then treat possibilities as probabilities. - Charles Dickens",
    "Learn as if you will live forever, live like you will die tomorrow. - Mahatma Gandhi",
    "It is only when we take chances, when our lives improve. The initial and the most difficult risk that we need to take is to become honest. - Walter Anderson",
    "All our dreams can come true if we have the courage to pursue them. - Walt Disney",
    "Move out of your comfort zone. You can only grow if you are willing to feel awkward and uncomfortable when you try something new. - Brian Tracy",
    "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    "Never bend your head. Always hold it high. Look the world straight in the eye. - Helen Keller",
    "We generate fears while we sit. We overcome them by action. Fear is nature’s way of warning us to get busy. - Dr. Henry Link",
    "The man who has confidence in himself gains the confidence of others. - Hasidic Proverb",
    "What you lack in talent can be made up with desire, hustle and giving 110% all the time. - Don Zimmer",
    "Fake it until you make it! Act as if you had all the confidence you require until it becomes your reality. - Brian Tracy",
    "Imperfection is beauty, madness is genius and it’s better to be absolutely ridiculous than absolutely boring. - Marilyn Monroe",
    "May your choices reflect your hopes, not your fears. - Nelson Mandela",
    "Remember always that you have not only the right to be an individual; you have an obligation to be one. You cannot make any useful contribution in life unless you do this. - Eleanor Roosevelt",
    "It takes courage to grow up and become who you really are. - E.E. Cummings",
    "You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win. - Zig Ziglar",
    "Perfection is not attainable, but if we chase perfection we can catch excellence. - Vince Lombardi",
    "Let us make our future now, and let us make our dreams tomorrow’s reality. - Malala Yousafzai",
    "The best way to get started is to quit talking and begin doing. - Walt Disney",
    "Leaders set high standards. Refuse to tolerate mediocrity or poor performance. - Brian Tracy",
    "It’s not whether you get knocked down, it’s whether you get back up. - Vince Lombardi",
    "It is often the small steps, not the giant leaps, that bring about the most lasting change. - Queen Elizabeth II",
    "When one door closes, sometimes we need to turn the knob to open another… - J.A. Tran",
    "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean",
    "Don’t Let Yesterday Take Up Too Much Of Today. - Will Rogers",
    "We may encounter many defeats but we must not be defeated. - Maya Angelou",
    "Leaders never use the word failure. They look upon setbacks as learning experiences. - Brian Tracy",
    "We become what we think about - Earl Nightingale",
    "There are no limits to what you can accomplish, except the limits you place on your own thinking. - Brian Tracy",
    "Inspiration comes from within yourself. One has to be positive. When you’re positive, good things happen. - Deep Roy",
    "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. - Helen Keller",
    "Develop an ‘attitude of gratitude.’ Say thank you to everyone you meet for everything you do. - Brian Tracy",
    "Today’s accomplishments were yesterday’s impossibilities. - Robert H. Schuller",
    "The future belongs to the competent. Get good, get better, be the best! - Brian Tracy",
    "Your success and happiness lies in you. Resolve to keep happy, and your joy and you shall form an invincible host against difficulties. - Helen Keller",
    "Courage is more exhilarating than fear and in the long run it is easier. We do not have to become heroes overnight. Just one step at a time, meeting each thing that comes up, seeing it is not as dreadful as it appeared, discovering we have the strength to stare it down. - Eleanor Roosevelt",
    "For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded. - Jack Canfield",
    "It is our attitude at the beginning of a difficult task which, more than anything else, will affect its successful outcome. - William James",
    "Belief creates the actual fact. - William James",
    "Act as if what you do makes a difference. It does. - William James",
    "The greatest weapon against stress is our ability to choose one thought over another. - William James",
    "If you can change your mind, you can change your life. - William James",
    "I learned this, at least, by my experiment: that if one advances confidently in the direction of his dreams, and endeavors to live the life which he has imagined, he will meet with a success unexpected in common hours. - Henry David Thoreau",
    "Dreams are the touchstones of our characters. - Henry David Thoreau",
    "If you have built castles in the air, your work need not be lost; that is where they should be. Now put the foundations under them. - Henry David Thoreau",
    "As if you could kill time without injuring eternity. - Henry David Thoreau",
    "There is no remedy for love but to love more. - Henry David Thoreau",
    "You define your own life. Don’t let other people write your script. - Oprah Winfrey",
    "Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness. - Oprah Winfrey",
    "Turn your wounds into wisdom. - Oprah Winfrey",
    "Doing the best at this moment puts you in the best place for the next moment. - Oprah Winfrey",
    "Real integrity is doing the right thing, knowing that nobody’s going to know whether you did it or not. - Oprah Winfrey",
    "Our greatest glory is not in never failing, but in rising up every time we fail. - Ralph Waldo Emerson",
    "Live in the sunshine, swim the sea, drink the wild air. - Ralph Waldo Emerson",
    "Nothing great was ever achieved without enthusiasm. - Ralph Waldo Emerson",
    "Life is a journey, not a destination. - Ralph Waldo Emerson",
    "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
    "Creativity is intelligence having fun. - Albert Einstein",
    "We cannot solve our problems with the same thinking we used to create them. - Albert Einstein",
    "Imagination is everything. It is the preview of life’s coming attractions. - Albert Einstein",
    "Anyone who has never made a mistake has never tried anything new. - Albert Einstein",
    "When a person really desires something, all the universe conspires to help that person to realize his dream. - Paulo Coelho",
    "Optimism is the one quality more associated with success and happiness than any other. - Brian Tracy",
    "While one person hesitates because he feels inferior, the other is busy making mistakes and becoming superior. - Henry Link",
    "Imagine your life is perfect in every respect; what would it look like? - Brian Tracy",
    "We all die. The goal isn’t to live forever, the goal is to create something that will. - Chuck Palahniuk",
    "My mission in life is not merely to survive, but to thrive. - Maya Angelou",
    "Knowing is not enough; we must apply. Wishing is not enough; we must do. - Johann Wolfgang Von Goethe",
    "Reading is to the mind, as exercise is to the body. - Brian Tracy",
    "You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction. - George Lorimer",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "Go as far as you can see; when you get there, you’ll be able to see further. - Thomas Carlyle",
    "Waiting insistently in front of a tightly closed door is unfair to all of the open doors! Give a chance to the open doors! - Mehmet Murat ildan",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "You have brains in your head. You have feet in your shoes. You can steer yourself in any direction you choose. You’re on your own, and you know what you know. And you are the guy who’ll decide where to go. - Dr. Seuss",
    "You make a choice: continue living your life feeling muddled in this abyss of self-misunderstanding, or you find your identity independent of it. You draw your own box. - Duchess Meghan",
    "The key responsibility of leadership is to think about the future. No one else can do it for you. - Brian Tracy",
    "Make your life a masterpiece, imagine no limitations on what you can be, have, or do. - Brian Tracy",
    "Perfection is not attainable, but if we chase perfection we can catch excellence. - Vince Lombardi",
    "Let us make our future now, and let us make our dreams tomorrow’s reality. - Malala Yousafzai",
    "The best way to get started is to quit talking and begin doing. - Walt Disney",
    "Leaders set high standards. Refuse to tolerate mediocrity or poor performance. - Brian Tracy",
    "It’s not whether you get knocked down, it’s whether you get back up. - Vince Lombardi",
    "It is often the small steps, not the giant leaps, that bring about the most lasting change. - Queen Elizabeth II",
    "When one door closes, sometimes we need to turn the knob to open another… - J.A. Tran",
    "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean",
    "Don’t Let Yesterday Take Up Too Much Of Today. - Will Rogers",
    "We may encounter many defeats but we must not be defeated. - Maya Angelou",
    "We become what we think about - Earl Nightingale",
    "There are no limits to what you can accomplish, except the limits you place on your own thinking. - Brian Tracy",
    "Inspiration comes from within yourself. One has to be positive. When you’re positive, good things happen. - Deep Roy",
    "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. - Helen Keller",
    "Develop an ‘attitude of gratitude.’ Say thank you to everyone you meet for everything you do. - Brian Tracy",
    "Today’s accomplishments were yesterday’s impossibilities. - Robert H. Schuller",
    "The future belongs to the competent. Get good, get better, be the best! - Brian Tracy",
    "Your success and happiness lies in you. Resolve to keep happy, and your joy and you shall form an invincible host against difficulties. - Helen Keller",
    "Courage is more exhilarating than fear and in the long run it is easier. We do not have to become heroes overnight. Just one step at a time, meeting each thing that comes up, seeing it is not as dreadful as it appeared, discovering we have the strength to stare it down. - Eleanor Roosevelt",
    "For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded. - Jack Canfield",
    "It is our attitude at the beginning of a difficult task which, more than anything else, will affect its successful outcome. - William James",
    "Belief creates the actual fact. - William James",
    "Act as if what you do makes a difference. It does. - William James",
    "The greatest weapon against stress is our ability to choose one thought over another. - William James",
    "If you can change your mind, you can change your life. - William James",
    "I learned this, at least, by my experiment: that if one advances confidently in the direction of his dreams, and endeavors to live the life which he has imagined, he will meet with a success unexpected in common hours. - Henry David Thoreau",
    "Dreams are the touchstones of our characters. - Henry David Thoreau",
    "If you have built castles in the air, your work need not be lost; that is where they should be. Now put the foundations under them. - Henry David Thoreau",
    "As if you could kill time without injuring eternity. - Henry David Thoreau",
    "There is no remedy for love but to love more. - Henry David Thoreau",
    "You define your own life. Don’t let other people write your script. - Oprah Winfrey",
    "Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness. - Oprah Winfrey",
    "Turn your wounds into wisdom. - Oprah Winfrey",
    "Doing the best at this moment puts you in the best place for the next moment. - Oprah Winfrey",
    "Real integrity is doing the right thing, knowing that nobody’s going to know whether you did it or not. - Oprah Winfrey",
    "Our greatest glory is not in never failing, but in rising up every time we fail. - Ralph Waldo Emerson",
    "Live in the sunshine, swim the sea, drink the wild air. - Ralph Waldo Emerson",
    "Nothing great was ever achieved without enthusiasm. - Ralph Waldo Emerson",
    "Life is a journey, not a destination. - Ralph Waldo Emerson",
    "Life is like riding a bicycle. To keep your balance, you must keep moving. - Albert Einstein",
    "Creativity is intelligence having fun. - Albert Einstein",
    "We cannot solve our problems with the same thinking we used to create them. - Albert Einstein",
    "Imagination is everything. It is the preview of life’s coming attractions. - Albert Einstein",
    "Anyone who has never made a mistake has never tried anything new. - Albert Einstein",
    "When a person really desires something, all the universe conspires to help that person to realize his dream. - Paulo Coelho",
    "Optimism is the one quality more associated with success and happiness than any other. - Brian Tracy",
    "While one person hesitates because he feels inferior, the other is busy making mistakes and becoming superior. - Henry Link",
    "Imagine your life is perfect in every respect; what would it look like? - Brian Tracy",
    "We all die. The goal isn’t to live forever, the goal is to create something that will. - Chuck Palahniuk",
    "My mission in life is not merely to survive, but to thrive. - Maya Angelou",
    "Knowing is not enough; we must apply. Wishing is not enough; we must do. - Johann Wolfgang Von Goethe",
    "Reading is to the mind, as exercise is to the body. - Brian Tracy",
    "You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction. - George Lorimer",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "Go as far as you can see; when you get there, you’ll be able to see further. - Thomas Carlyle",

];


var Num = 0;
var output = "";




function quote()
{
    Num = Math.floor(Math.random()*quotes.length);
    console.log(Num);
    output = quotes[Num];
    document.getElementById("qot").innerHTML = output;
}